repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: ruff
        name: ruff-check
        entry: 'ruff'
        language: system
        args: ['check', '.']
        pass_filenames: false
        types: [python]
      - id: ruff
        name: ruff-fix
        entry: 'ruff'
        language: system
        args: ['check', '--fix', '.']
        pass_filenames: false
        types: [python]