services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    depends_on:
      - backend