services:
  api:
    container_name: api
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file: ../.env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  database:
    container_name: database
    image: postgres:16.9-bullseye
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: ../.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
